use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use serde_json::{json, Map, Value};
use videola_core::command::{Command, ALL_COMMAND_LABELS};

// The command catalogue the HTTP interface and the MCP server hand out. It is generated rather
// than written by hand for the reason the design document gives: a new command must reach every
// consumer without anyone maintaining a second list. `schemars` reads the same `#[serde]`
// attributes `serde_json` obeys, so the property names in here are the ones the core accepts.
#[test]
fn the_generated_catalogue_covers_every_command_the_core_knows() {
    let schema = serde_json::to_value(schemars::schema_for!(Command)).expect("schema to json");
    let defs = schema["$defs"].as_object().cloned().unwrap_or_default();
    let variants = schema["oneOf"].as_array().expect("an enum of variants");

    let entries: Vec<Entry> = variants
        .iter()
        .map(|variant| entry(variant, &defs))
        .collect();

    let generated: BTreeSet<&str> = entries.iter().map(|entry| entry.command.as_str()).collect();
    let known: BTreeSet<String> = ALL_COMMAND_LABELS
        .iter()
        .map(|label| label.trim_start_matches("cmd.").to_string())
        .collect();
    let known: BTreeSet<&str> = known.iter().map(String::as_str).collect();
    assert_eq!(
        generated, known,
        "the catalogue and ALL_COMMAND_LABELS must name the same commands"
    );

    let out = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/server/src/generated/commandCatalog.ts");
    std::fs::create_dir_all(out.parent().expect("a parent directory")).expect("create out dir");
    std::fs::write(out, typescript(&entries)).expect("write catalogue");
}

struct Entry {
    command: String,
    description: String,
    schema: Value,
}

// Each command carries only the definitions it can actually reach. Handing every tool the whole
// model would put the same few thousand lines in front of an agent twenty-six times over, for a
// command whose entire payload is one id.
fn entry(variant: &Value, defs: &Map<String, Value>) -> Entry {
    let Some(command) = variant["properties"]["type"]["const"].as_str() else {
        panic!("every Command variant is internally tagged, this one is not: {variant}")
    };
    let command = command.to_string();

    let mut schema = variant.clone();
    let reachable = reachable_defs(variant, defs);
    if !reachable.is_empty() {
        schema["$defs"] = Value::Object(reachable.into_iter().collect::<Map<_, _>>());
    }
    schema["$schema"] = json!("https://json-schema.org/draft/2020-12/schema");

    Entry {
        description: variant["description"]
            .as_str()
            .unwrap_or_default()
            .to_string(),
        command,
        schema,
    }
}

fn reachable_defs(from: &Value, defs: &Map<String, Value>) -> BTreeMap<String, Value> {
    let mut found = BTreeMap::new();
    let mut pending: Vec<String> = referenced_names(from);
    while let Some(name) = pending.pop() {
        if found.contains_key(&name) {
            continue;
        }
        let Some(def) = defs.get(&name) else { continue };
        pending.extend(referenced_names(def));
        found.insert(name, def.clone());
    }
    found
}

fn referenced_names(value: &Value) -> Vec<String> {
    match value {
        Value::Object(fields) => fields
            .iter()
            .flat_map(|(key, nested)| match (key.as_str(), nested.as_str()) {
                ("$ref", Some(target)) => target
                    .strip_prefix("#/$defs/")
                    .map(|name| vec![name.to_string()])
                    .unwrap_or_default(),
                _ => referenced_names(nested),
            })
            .collect(),
        Value::Array(items) => items.iter().flat_map(referenced_names).collect(),
        _ => Vec::new(),
    }
}

fn typescript(entries: &[Entry]) -> String {
    let body = entries
        .iter()
        .map(|entry| {
            format!(
                "  {{\n    command: {},\n    description: {},\n    schema: {},\n  }},",
                json!(entry.command),
                json!(entry.description),
                // Infallible where `serde_json::to_string` is not: the schema is already a `Value`.
                entry.schema
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "// Generated by `cargo test -p videola-core --test export_catalog`. Do not edit by hand.\n\
         export interface CommandSchema {{\n\
        \x20 readonly command: string;\n\
        \x20 readonly description: string;\n\
        \x20 readonly schema: Record<string, unknown>;\n\
         }}\n\n\
         export const COMMAND_CATALOG: readonly CommandSchema[] = [\n{body}\n];\n"
    )
}
